spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123
    url: jdbc:mysql://localhost:3306/cinema?serverTimezone=GMT%2B8
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.woniu.woniuticket.user.dao.*